### ISSUE TITLE
No autocomplete for sub-classes on scss

### ISSUE THREAD

**Issue by Kcko** [gencer/HTML-Slim-CSS-SCSS-Class-Completion#19] opened 2019-02-14 10:15 UTC
Hi gencer,

with today i started work on new project and i see a strange behavior with some mistakes 
which were to be corrected in the previous commits / issues.

Video + explanation inside ... http://bit.ly/2S524WJ 

:-(

**Comment by gencer** [comment] 2019-02-14 10:33
This is not a bug but a missing feature.

To autocomplete such SCSS selectors, we need to compile SCSS first.

For example;

.class { // We can auto complete this.
  &--connected {
    // we cannot know this until SCSS compiled.
  }
}

But I think I can hack into it and show such completions. Let me do some demos on my end and update here.


What I can do here is, hack into such completions and merge myself in parser. This can be done. But need a work to do.

**Comment by Kcko** [comment] 2019-02-14 10:35
In video you can see that im using app.css in project (where is everything after scss compilation).

**Comment by Kcko** [comment] 2019-02-14 10:36
And it works on previous project (plugin show completitions for latte / php / css ) 
and when im setup scssUsing : true also in scss files.
Now its works strangely.

**Comment by gencer** [comment] 2019-02-14 10:37
Are you sure that file is indexed by this extension? Is it local? Can you send me that file via email again? If it works on my end then this files does not get indexed in your workspace.

**Comment by gencer** [comment] 2019-02-14 10:37
So it works with that option?

**Comment by gencer** [comment] 2019-02-14 10:44
Ah and one more thing:

As you know we introduced incremental build that's mean when you change something after VSCode opens, we will include that changes.

This does not counts changed files on disk.  This means, If you build that `app.css` files via gulp or something, vscode will not see that file. You need to click action button bottom of vscode. Try this. If it works, I will add this event to vscode.

**Comment by imichall** [comment] 2019-02-14 10:48
> Ah and one more thing:
> 
> As you know we introduced incremental build that's mean when you change something after VSCode opens, we will include that changes.
> 
> This does not counts changed files on disk. This means, If you build that `app.css` files via gulp or something, vscode will not see that file. You need to click action button bottom of vscode. Try this. If it works, I will add this event to vscode.

Yeah, it should be the problem @Kcko. Otherwise, will be this function added as feature into this extension as automatically? That will be watching changing files / dirs like a gulp or something like that? Just question.

**Comment by gencer** [comment] 2019-02-14 10:51
> Yeah, it should be the problem @Kcko. Otherwise, will be this function added as feature into this extension as automatically? That will be watching changing files / dirs like a gulp or something like that? Just question.

Yup. That was what I am thinking of. I will watch changed files on disk. But I need @kcko to confirm this. He probably restarted vscode thats why it did worked on second time -not by option-. Because next time he start vscodei `app.css` was there already.

**Comment by Kcko** [comment] 2019-02-14 11:19
## Project eshop: (buggy)
css file here: http://nette-bootstrap.r.dev7.andweb.cz/assets/css/dev/app.css?1550137895
new video here: http://bit.ly/2X2m7c0

of course i press "uncache" btn on the bottom of VSC  and after for sure I restarted VSC a several times - without change.

All files ale local.

**Comment by Kcko** [comment] 2019-02-14 11:28
Soccer project: (buggy less)
Video: http://bit.ly/2WYWYyK

Still with ```"html-css-class-completion.enableScssFindUsage": false```

classes from BS are visible but occurences are only in (latte / php / html)
css -> missing -> bad (we set findUsage on false, but this should control only scss file)
scss -> missing -> godd (because we set findUsage on false)

Some idea whats bad?

**Comment by Kcko** [comment] 2019-02-14 11:31
and one small piece at the end, when i wrote exact name for class, it never on first position on the list.

**Comment by gencer** [comment] 2019-02-14 11:38
I will look into this and release new version.

> ## Soccer project: (buggy less)
> Video: http://bit.ly/2WYWYyK
> 
> Still with `"html-css-class-completion.enableScssFindUsage": false`
> 
> classes from BS are visible but occurences are only in (latte / php / html)
> css -> missing -> bad (we set findUsage on false, but this should control only scss file)
> scss -> missing -> godd (because we set findUsage on false)
> 
> Some idea whats bad?

It will be fixed in next build.

**Comment by gencer** [comment] 2019-02-14 11:39
> ## Project eshop: (buggy)
> css file here: http://nette-bootstrap.r.dev7.andweb.cz/assets/css/dev/app.css?1550137895
> new video here: http://bit.ly/2X2m7c0
> 
> of course i press "uncache" btn on the bottom of VSC and after for sure I restarted VSC a several times - without change.
> 
> All files ale local.

I will look deeper on this.

**Comment by Kcko** [comment] 2019-02-14 11:46
So we should be clear about the behavior of plugin, I'm already losing myself.

It should works like that:

## default behavior
Autocompletition for 
 - latte
 - html
 - php
 - whatever without scss (because it slows down performance, can be solved at future)

When i add / change / delete some class or id in css file, it will rescan only file where i did it. 
Fullscan will run only once (when i loaded project / workspace at first).


When i set ````"html-css-class-completion.enableScssFindUsage": false``` autocompletition will work on scss file now +  will show occurences also.

Is it allright like this?

**Comment by gencer** [comment] 2019-02-14 12:24
Yes but i think you misunderstood how enableScssFindUsage works? I will explain in detail on readme later.

**Closed** 2019-05-28 18:32 UTC
Labels: bug, enhancement
